/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRetencionesRouteImport } from './routes/_authenticated/retenciones'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedPlanCuentasRouteImport } from './routes/_authenticated/plan-cuentas'
import { Route as AuthenticatedLibroVentasRouteImport } from './routes/_authenticated/libro-ventas'
import { Route as AuthenticatedLibroComprasRouteImport } from './routes/_authenticated/libro-compras'
import { Route as AuthenticatedFacturacionRouteImport } from './routes/_authenticated/facturacion'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated/equipo'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCentrosCostoRouteImport } from './routes/_authenticated/centros-costo'
import { Route as AuthenticatedAsientosRouteImport } from './routes/_authenticated/asientos'
import { Route as AuthenticatedInformesIndexRouteImport } from './routes/_authenticated/informes.index'
import { Route as AuthenticatedInformesMayorRouteImport } from './routes/_authenticated/informes.mayor'
import { Route as AuthenticatedInformesEstadoResultadosRouteImport } from './routes/_authenticated/informes.estado-resultados'
import { Route as AuthenticatedInformesDiarioRouteImport } from './routes/_authenticated/informes.diario'
import { Route as AuthenticatedInformesDeclaracionIvaRouteImport } from './routes/_authenticated/informes.declaracion-iva'
import { Route as AuthenticatedInformesComprobacionRouteImport } from './routes/_authenticated/informes.comprobacion'
import { Route as AuthenticatedInformesBalanceGeneralRouteImport } from './routes/_authenticated/informes.balance-general'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRetencionesRoute =
  AuthenticatedRetencionesRouteImport.update({
    id: '/retenciones',
    path: '/retenciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanCuentasRoute =
  AuthenticatedPlanCuentasRouteImport.update({
    id: '/plan-cuentas',
    path: '/plan-cuentas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibroVentasRoute =
  AuthenticatedLibroVentasRouteImport.update({
    id: '/libro-ventas',
    path: '/libro-ventas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibroComprasRoute =
  AuthenticatedLibroComprasRouteImport.update({
    id: '/libro-compras',
    path: '/libro-compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturacionRoute =
  AuthenticatedFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentrosCostoRoute =
  AuthenticatedCentrosCostoRouteImport.update({
    id: '/centros-costo',
    path: '/centros-costo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAsientosRoute = AuthenticatedAsientosRouteImport.update({
  id: '/asientos',
  path: '/asientos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInformesIndexRoute =
  AuthenticatedInformesIndexRouteImport.update({
    id: '/informes/',
    path: '/informes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformesMayorRoute =
  AuthenticatedInformesMayorRouteImport.update({
    id: '/informes/mayor',
    path: '/informes/mayor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformesEstadoResultadosRoute =
  AuthenticatedInformesEstadoResultadosRouteImport.update({
    id: '/informes/estado-resultados',
    path: '/informes/estado-resultados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformesDiarioRoute =
  AuthenticatedInformesDiarioRouteImport.update({
    id: '/informes/diario',
    path: '/informes/diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformesDeclaracionIvaRoute =
  AuthenticatedInformesDeclaracionIvaRouteImport.update({
    id: '/informes/declaracion-iva',
    path: '/informes/declaracion-iva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformesComprobacionRoute =
  AuthenticatedInformesComprobacionRouteImport.update({
    id: '/informes/comprobacion',
    path: '/informes/comprobacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformesBalanceGeneralRoute =
  AuthenticatedInformesBalanceGeneralRouteImport.update({
    id: '/informes/balance-general',
    path: '/informes/balance-general',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/asientos': typeof AuthenticatedAsientosRoute
  '/centros-costo': typeof AuthenticatedCentrosCostoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/facturacion': typeof AuthenticatedFacturacionRoute
  '/libro-compras': typeof AuthenticatedLibroComprasRoute
  '/libro-ventas': typeof AuthenticatedLibroVentasRoute
  '/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/retenciones': typeof AuthenticatedRetencionesRoute
  '/informes/balance-general': typeof AuthenticatedInformesBalanceGeneralRoute
  '/informes/comprobacion': typeof AuthenticatedInformesComprobacionRoute
  '/informes/declaracion-iva': typeof AuthenticatedInformesDeclaracionIvaRoute
  '/informes/diario': typeof AuthenticatedInformesDiarioRoute
  '/informes/estado-resultados': typeof AuthenticatedInformesEstadoResultadosRoute
  '/informes/mayor': typeof AuthenticatedInformesMayorRoute
  '/informes/': typeof AuthenticatedInformesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/asientos': typeof AuthenticatedAsientosRoute
  '/centros-costo': typeof AuthenticatedCentrosCostoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/facturacion': typeof AuthenticatedFacturacionRoute
  '/libro-compras': typeof AuthenticatedLibroComprasRoute
  '/libro-ventas': typeof AuthenticatedLibroVentasRoute
  '/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/retenciones': typeof AuthenticatedRetencionesRoute
  '/informes/balance-general': typeof AuthenticatedInformesBalanceGeneralRoute
  '/informes/comprobacion': typeof AuthenticatedInformesComprobacionRoute
  '/informes/declaracion-iva': typeof AuthenticatedInformesDeclaracionIvaRoute
  '/informes/diario': typeof AuthenticatedInformesDiarioRoute
  '/informes/estado-resultados': typeof AuthenticatedInformesEstadoResultadosRoute
  '/informes/mayor': typeof AuthenticatedInformesMayorRoute
  '/informes': typeof AuthenticatedInformesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/asientos': typeof AuthenticatedAsientosRoute
  '/_authenticated/centros-costo': typeof AuthenticatedCentrosCostoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/facturacion': typeof AuthenticatedFacturacionRoute
  '/_authenticated/libro-compras': typeof AuthenticatedLibroComprasRoute
  '/_authenticated/libro-ventas': typeof AuthenticatedLibroVentasRoute
  '/_authenticated/plan-cuentas': typeof AuthenticatedPlanCuentasRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/retenciones': typeof AuthenticatedRetencionesRoute
  '/_authenticated/informes/balance-general': typeof AuthenticatedInformesBalanceGeneralRoute
  '/_authenticated/informes/comprobacion': typeof AuthenticatedInformesComprobacionRoute
  '/_authenticated/informes/declaracion-iva': typeof AuthenticatedInformesDeclaracionIvaRoute
  '/_authenticated/informes/diario': typeof AuthenticatedInformesDiarioRoute
  '/_authenticated/informes/estado-resultados': typeof AuthenticatedInformesEstadoResultadosRoute
  '/_authenticated/informes/mayor': typeof AuthenticatedInformesMayorRoute
  '/_authenticated/informes/': typeof AuthenticatedInformesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/asientos'
    | '/centros-costo'
    | '/clientes'
    | '/compras'
    | '/dashboard'
    | '/empresas'
    | '/equipo'
    | '/facturacion'
    | '/libro-compras'
    | '/libro-ventas'
    | '/plan-cuentas'
    | '/proveedores'
    | '/retenciones'
    | '/informes/balance-general'
    | '/informes/comprobacion'
    | '/informes/declaracion-iva'
    | '/informes/diario'
    | '/informes/estado-resultados'
    | '/informes/mayor'
    | '/informes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/asientos'
    | '/centros-costo'
    | '/clientes'
    | '/compras'
    | '/dashboard'
    | '/empresas'
    | '/equipo'
    | '/facturacion'
    | '/libro-compras'
    | '/libro-ventas'
    | '/plan-cuentas'
    | '/proveedores'
    | '/retenciones'
    | '/informes/balance-general'
    | '/informes/comprobacion'
    | '/informes/declaracion-iva'
    | '/informes/diario'
    | '/informes/estado-resultados'
    | '/informes/mayor'
    | '/informes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/asientos'
    | '/_authenticated/centros-costo'
    | '/_authenticated/clientes'
    | '/_authenticated/compras'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/equipo'
    | '/_authenticated/facturacion'
    | '/_authenticated/libro-compras'
    | '/_authenticated/libro-ventas'
    | '/_authenticated/plan-cuentas'
    | '/_authenticated/proveedores'
    | '/_authenticated/retenciones'
    | '/_authenticated/informes/balance-general'
    | '/_authenticated/informes/comprobacion'
    | '/_authenticated/informes/declaracion-iva'
    | '/_authenticated/informes/diario'
    | '/_authenticated/informes/estado-resultados'
    | '/_authenticated/informes/mayor'
    | '/_authenticated/informes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/retenciones': {
      id: '/_authenticated/retenciones'
      path: '/retenciones'
      fullPath: '/retenciones'
      preLoaderRoute: typeof AuthenticatedRetencionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan-cuentas': {
      id: '/_authenticated/plan-cuentas'
      path: '/plan-cuentas'
      fullPath: '/plan-cuentas'
      preLoaderRoute: typeof AuthenticatedPlanCuentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libro-ventas': {
      id: '/_authenticated/libro-ventas'
      path: '/libro-ventas'
      fullPath: '/libro-ventas'
      preLoaderRoute: typeof AuthenticatedLibroVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libro-compras': {
      id: '/_authenticated/libro-compras'
      path: '/libro-compras'
      fullPath: '/libro-compras'
      preLoaderRoute: typeof AuthenticatedLibroComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturacion': {
      id: '/_authenticated/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AuthenticatedFacturacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-costo': {
      id: '/_authenticated/centros-costo'
      path: '/centros-costo'
      fullPath: '/centros-costo'
      preLoaderRoute: typeof AuthenticatedCentrosCostoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asientos': {
      id: '/_authenticated/asientos'
      path: '/asientos'
      fullPath: '/asientos'
      preLoaderRoute: typeof AuthenticatedAsientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes/': {
      id: '/_authenticated/informes/'
      path: '/informes'
      fullPath: '/informes/'
      preLoaderRoute: typeof AuthenticatedInformesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes/mayor': {
      id: '/_authenticated/informes/mayor'
      path: '/informes/mayor'
      fullPath: '/informes/mayor'
      preLoaderRoute: typeof AuthenticatedInformesMayorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes/estado-resultados': {
      id: '/_authenticated/informes/estado-resultados'
      path: '/informes/estado-resultados'
      fullPath: '/informes/estado-resultados'
      preLoaderRoute: typeof AuthenticatedInformesEstadoResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes/diario': {
      id: '/_authenticated/informes/diario'
      path: '/informes/diario'
      fullPath: '/informes/diario'
      preLoaderRoute: typeof AuthenticatedInformesDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes/declaracion-iva': {
      id: '/_authenticated/informes/declaracion-iva'
      path: '/informes/declaracion-iva'
      fullPath: '/informes/declaracion-iva'
      preLoaderRoute: typeof AuthenticatedInformesDeclaracionIvaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes/comprobacion': {
      id: '/_authenticated/informes/comprobacion'
      path: '/informes/comprobacion'
      fullPath: '/informes/comprobacion'
      preLoaderRoute: typeof AuthenticatedInformesComprobacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes/balance-general': {
      id: '/_authenticated/informes/balance-general'
      path: '/informes/balance-general'
      fullPath: '/informes/balance-general'
      preLoaderRoute: typeof AuthenticatedInformesBalanceGeneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAsientosRoute: typeof AuthenticatedAsientosRoute
  AuthenticatedCentrosCostoRoute: typeof AuthenticatedCentrosCostoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedFacturacionRoute: typeof AuthenticatedFacturacionRoute
  AuthenticatedLibroComprasRoute: typeof AuthenticatedLibroComprasRoute
  AuthenticatedLibroVentasRoute: typeof AuthenticatedLibroVentasRoute
  AuthenticatedPlanCuentasRoute: typeof AuthenticatedPlanCuentasRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRetencionesRoute: typeof AuthenticatedRetencionesRoute
  AuthenticatedInformesBalanceGeneralRoute: typeof AuthenticatedInformesBalanceGeneralRoute
  AuthenticatedInformesComprobacionRoute: typeof AuthenticatedInformesComprobacionRoute
  AuthenticatedInformesDeclaracionIvaRoute: typeof AuthenticatedInformesDeclaracionIvaRoute
  AuthenticatedInformesDiarioRoute: typeof AuthenticatedInformesDiarioRoute
  AuthenticatedInformesEstadoResultadosRoute: typeof AuthenticatedInformesEstadoResultadosRoute
  AuthenticatedInformesMayorRoute: typeof AuthenticatedInformesMayorRoute
  AuthenticatedInformesIndexRoute: typeof AuthenticatedInformesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAsientosRoute: AuthenticatedAsientosRoute,
  AuthenticatedCentrosCostoRoute: AuthenticatedCentrosCostoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedFacturacionRoute: AuthenticatedFacturacionRoute,
  AuthenticatedLibroComprasRoute: AuthenticatedLibroComprasRoute,
  AuthenticatedLibroVentasRoute: AuthenticatedLibroVentasRoute,
  AuthenticatedPlanCuentasRoute: AuthenticatedPlanCuentasRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRetencionesRoute: AuthenticatedRetencionesRoute,
  AuthenticatedInformesBalanceGeneralRoute:
    AuthenticatedInformesBalanceGeneralRoute,
  AuthenticatedInformesComprobacionRoute:
    AuthenticatedInformesComprobacionRoute,
  AuthenticatedInformesDeclaracionIvaRoute:
    AuthenticatedInformesDeclaracionIvaRoute,
  AuthenticatedInformesDiarioRoute: AuthenticatedInformesDiarioRoute,
  AuthenticatedInformesEstadoResultadosRoute:
    AuthenticatedInformesEstadoResultadosRoute,
  AuthenticatedInformesMayorRoute: AuthenticatedInformesMayorRoute,
  AuthenticatedInformesIndexRoute: AuthenticatedInformesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
