/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRetencionesRouteImport } from './routes/_authenticated/retenciones'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedLibroVentasRouteImport } from './routes/_authenticated/libro-ventas'
import { Route as AuthenticatedLibroComprasRouteImport } from './routes/_authenticated/libro-compras'
import { Route as AuthenticatedFacturacionRouteImport } from './routes/_authenticated/facturacion'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated/equipo'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRetencionesRoute =
  AuthenticatedRetencionesRouteImport.update({
    id: '/retenciones',
    path: '/retenciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibroVentasRoute =
  AuthenticatedLibroVentasRouteImport.update({
    id: '/libro-ventas',
    path: '/libro-ventas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibroComprasRoute =
  AuthenticatedLibroComprasRouteImport.update({
    id: '/libro-compras',
    path: '/libro-compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturacionRoute =
  AuthenticatedFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/facturacion': typeof AuthenticatedFacturacionRoute
  '/libro-compras': typeof AuthenticatedLibroComprasRoute
  '/libro-ventas': typeof AuthenticatedLibroVentasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/retenciones': typeof AuthenticatedRetencionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/facturacion': typeof AuthenticatedFacturacionRoute
  '/libro-compras': typeof AuthenticatedLibroComprasRoute
  '/libro-ventas': typeof AuthenticatedLibroVentasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/retenciones': typeof AuthenticatedRetencionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/facturacion': typeof AuthenticatedFacturacionRoute
  '/_authenticated/libro-compras': typeof AuthenticatedLibroComprasRoute
  '/_authenticated/libro-ventas': typeof AuthenticatedLibroVentasRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/retenciones': typeof AuthenticatedRetencionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/compras'
    | '/dashboard'
    | '/empresas'
    | '/equipo'
    | '/facturacion'
    | '/libro-compras'
    | '/libro-ventas'
    | '/proveedores'
    | '/retenciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/compras'
    | '/dashboard'
    | '/empresas'
    | '/equipo'
    | '/facturacion'
    | '/libro-compras'
    | '/libro-ventas'
    | '/proveedores'
    | '/retenciones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/compras'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/equipo'
    | '/_authenticated/facturacion'
    | '/_authenticated/libro-compras'
    | '/_authenticated/libro-ventas'
    | '/_authenticated/proveedores'
    | '/_authenticated/retenciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/retenciones': {
      id: '/_authenticated/retenciones'
      path: '/retenciones'
      fullPath: '/retenciones'
      preLoaderRoute: typeof AuthenticatedRetencionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libro-ventas': {
      id: '/_authenticated/libro-ventas'
      path: '/libro-ventas'
      fullPath: '/libro-ventas'
      preLoaderRoute: typeof AuthenticatedLibroVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libro-compras': {
      id: '/_authenticated/libro-compras'
      path: '/libro-compras'
      fullPath: '/libro-compras'
      preLoaderRoute: typeof AuthenticatedLibroComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturacion': {
      id: '/_authenticated/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AuthenticatedFacturacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedFacturacionRoute: typeof AuthenticatedFacturacionRoute
  AuthenticatedLibroComprasRoute: typeof AuthenticatedLibroComprasRoute
  AuthenticatedLibroVentasRoute: typeof AuthenticatedLibroVentasRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRetencionesRoute: typeof AuthenticatedRetencionesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedFacturacionRoute: AuthenticatedFacturacionRoute,
  AuthenticatedLibroComprasRoute: AuthenticatedLibroComprasRoute,
  AuthenticatedLibroVentasRoute: AuthenticatedLibroVentasRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRetencionesRoute: AuthenticatedRetencionesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
